import { useEffect, useState } from "react";
import PageHeader from "@/utils/PageHeader";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useDispatch, useSelector } from "react-redux";
import { PagesDataHandler } from "@/redux/actions/PagesApi";
import DOMPurify from "dompurify";

const ReturnPolicy = () => {

    const { t } = useTranslation();

    const dispatch = useDispatch();

    const { SinglePageData } = useSelector((state) => state.pagesData);

    const [loader, setLoader] = useState(true);

    useEffect(() => {
        dispatch(PagesDataHandler("return-policy", () => {
            setLoader(false);
        }));
    }, []);

    return (
        <>
            <Head>
                <title>{`${t('menu:return_policy')} - ${t('common:site_name')}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta property="og:title" content="" />
                <meta property="og:type" content="" />
                <meta property="og:url" content="" />
                <meta property="og:image" content="" />
                <link rel="icon" href="/fav.png" />
            </Head>
            <PageHeader title={t('menu:return_policy')} subTitle={t('menu:return_policy')} />
            <section className="pages">
                <div className="container">
                    <div className="card">
                        {SinglePageData?.content && (
                            <div
                                dangerouslySetInnerHTML={{
                                    __html: DOMPurify.sanitize(SinglePageData.content.replace(/(\d+\.)/g, "<br/><br/>$1"))
                                }}
                            ></div>
                        )}
                    </div>
                </div>
            </section>
        </>
    )
}

export default ReturnPolicy;

export async function getStaticProps({ locale }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ["menu", "common", "header"])),
        },
    };
}