import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import PageHeader from "@/utils/PageHeader";
import Link from "next/link";
import Image from "next/image";
import CatImage from '../../../public/images/general/cats/cat-12.png';

const Categories = () => {

    const { t } = useTranslation('menu');

    return(
        <>
            <Head>
                <title>{t('menu:all_categories')} - {t('common:site_name')}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta property="og:title" content="" />
                <meta property="og:type" content="" />
                <meta property="og:url" content="" />
                <meta property="og:image" content="" />
                <link rel="icon" href="/fav.png" />
            </Head>
            <PageHeader title="All Categories" />
            <div className="container-fluid">
                <div className="categories">
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                    <Link href="#" className="categories-box">
                        <div className="cat-image">
                            <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                        </div>
                        <div className="cat-title">Oganic Kiwi</div>
                    </Link>
                        <Link href="#" className="categories-box">
                            <div className="cat-image">
                                <Image src={CatImage} alt="Cat Name" width={80} height={80} />
                            </div>
                            <div className="cat-title">Oganic Kiwi</div>
                        </Link>
                </div>
            </div>
        </>
    )
}

export default Categories;

export async function getStaticProps({ locale }) {
    return {
        props: {
        ...(await serverSideTranslations(locale, ["auth", "menu", "common", "header"])),
        },
    };
  }