import dynamic from 'next/dynamic';
import Hero from '@/components/Hero';
import HomeFeaturedCategories from '@/components/HomeFeaturedCategories';
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from 'next/head';
import MobileAppBanner from './mobile_banner';

// const FlashSale = dynamic(() => import('@/components/FlashSale'), { ssr: false });
import FlashSale from "@/components/FlashSale";
const TopBrands = dynamic(() => import('@/components/TopBrands'), { ssr: false });
const PromoBanner = dynamic(() => import('@/components/PromoBanner'), { ssr: false });
const TopDeals = dynamic(() => import('@/components/TopDeals'), { ssr: false });

export default function Home() {

  return (
    <>
      <Head>
        <title>El Fergany Hyper Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Hero />
      <HomeFeaturedCategories />
      <FlashSale/>
      <TopBrands />
       <PromoBanner/>
      <TopDeals />
      <MobileAppBanner/> 
    </>
  )
}

export async function getStaticProps({ locale }) {
  return {
      props: {
      ...(await serverSideTranslations(locale, ["auth", "menu", "common", "header", "product"])),
      },
  };
}