import Head from "next/head";

const SeoHead = () => {

    return(
        <Head>
            <title>El Fergany Hyper Market</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta property="og:title" content="" />
            <meta property="og:type" content="" />
            <meta property="og:url" content="" />
            <meta property="og:image" content="" />
            <link rel="icon" href="/fav.png" />
        </Head>
    )
}

export default SeoHead;